### ISSUE TITLE
Code issue - Result Sets - Reading from multiple rows in database

### ISSUE THREAD

**Issue by presssyy** [JDrapes/WEDA-MVC#7] opened 2019-11-27 13:42 UTC
Hi Gents, there is currently an issue with the readability to the database as it only reads the top row, spotted by Jordan. I've tried to solve this error but I'm having no luck with solving this issue. This code is within the LoginController java file. Line 46 is the code that should enable the result set to loop through the entire database but this isnt the case as testing results in a fail. If anyone can have a look at this to try spot the mistake I'm missing that would be appreciated.

**Comment by GraingerBoii** [comment] 2019-11-27 13:46
Hi Alex,

I had a look at the code and noticed that the issue is that while checking the entries in the database, your else statement resets the page, and as a result exits the loop if the first entry doesn't match. By moving the event of the else statement outside the loop, it checks all entries, if an entry is correct it will move to the login page, if non are correct it will exit the loop and run the code for incorrect details.

**Comment by JDrapes** [comment] 2019-11-29 13:15
Solved - closing comment

**Closed as completed by JDrapes** 2019-11-29 13:15 UTC
